parameters:
    database_driver: pdo_mysql
    database_host: %DB_HOST% 
    database_port: %DB_PORT%
    database_name: %DB_NAME%
    database_user: %DB_USER%
    database_password: %DB_PASSWORD%
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_port: null
    mailer_encryption: null
    mailer_user: null
    mailer_password: null
    websocket_host: 0.0.0.0
    websocket_port: 8080
    session_handler: session.handler.native_file
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    installed: null
